### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by joemarlo** [joemarlo/plotBart#1]
- [ ] Write vignette @gperrett @joemarlo 
- [x] Remove overlapping functions from thinkCausal repo by Wednesday 10/13 @gperrett 
- [x] Fix issue in plot_variable_importance with variables getting drop from tree @gperrett 
- [x] Review default plot subtitles @gperrett @joemarlo 
- [x] Review API and ensure is consistent @joemarlo 
- [x] Review code coverage @joemarlo 
- [x] Manually review accuracy of each function output @gperrett @joemarlo 
- [x] Review all function manuals @joemarlo
